### ISSUE TITLE
0xFF value at end of file

### ISSUE THREAD

**Issue by SadE54** [joembedded/JesFs#6]
Hi, 

I'm searching for an embedded file system to write arbitrary binary data . i looked at the documentation file and I'm  not sure to understand . It's mandatory for you file system to avoid 0xff at the end of the files ? 🤔

**Comment by joembedded** [comment]
No, 0xFF is only for 'unclosed' files (where data can be added to the file without closing it (= faster and no erase for Flash memory required). It is possible to write binary files as 'unclosed' files conatining 0xFF, if you escape it. E.g. for 0xFF write 0xFE 0x01 and for 0xFE write 0x00.

**Comment by joembedded** [comment]
(This is from the docu)
