### ISSUE TITLE
Does the library support 64k sector size?

### ISSUE THREAD

**Issue by avinashraja98** [joembedded/JesFs#8]
I was wondering if I can use this library to interface with a Micron N25Q128 flash. It has 64k erase sectors and I noticed this library hard codes erase sector size to 4k. Thanks!

**Comment by joembedded** [comment]
Hmm, no. Almost all modern Flash allow 4k sector erase. However, the N25Q128 is not a good choice for LowPower, because ist has a high Standby /Deep Power down current.
